/**
Template Controllers

@module Templates
*/

/**
The chats aside template

@class [template] views_chats_aside
@constructor
*/


Template['views_chats_aside'].helpers({
    /**
    Get all my chats

    @method (chats)
    */
    'chats': function(){
        return Chats.find({}, {sort: {lastActivity: -1}});
    },
    /**
    Generate the chat name, based on all participants names

    @method (generatedName)
    */
    'generatedName': function(){
        if(_.isArray(this.users)) {
            var users = Users.find({_id: {$in: this.users}}).fetch();

            if(!_.isEmpty(users))
                return _.trim(_.pluck(users, 'name').join(', '),', ');
        }

        // return default name, if it couldn't be autogenerated
        return this._id;
    },
    /**
    Get all my chats

    @method (chats)
    */
    'unreadCount': function(){
        if(_.isArray(this.messages))
            return Messages.find({_id: {$in: this.messages}, unread: true}).count();
    }
});


Template['views_chats_aside'].events({
    /**
    Add a new chat by generating a new session key and route to the add user screen.

    @event click button.add-chat
    */
    'click button.add-chat': function(e){

        var sessionKey = Random.id();
        
        // create a new chat
        Router.go('chat', {sessionKey: sessionKey});

        // and immediately after, show the invite screen
        Meteor.setTimeout(function(){
            Router.go('createChat', {sessionKey: sessionKey});
        }, 10);
    }
});